f_name_template: "/global/cfs/cdirs/lsst/groups/WL/projects/wl-massmap/IA-infusion/SkySim5000/GalCat/HOD/FromCharlie/GalCat_tomo{}_06GpAM_new.dat"
n_tomo: 5
output: "/pscratch/sd/v/vanalfen/skysim_tomo/test.h5"